options:
  relay-port:
    type: int
    default: 9001
    description: "Weechat relay port"
  relay-password:
    type: string
    default: ""
    description: "Password for relay, blank to generate one automatically"
  enable-relay:
    type: boolean
    default: True
    description: "Enable weechat relay"
  user-config:
    type: string
    default: ""
    description: |
      Custom config for weechat. One command per line, ex:
      /server add freenode chat.freenode.net/6697 -ssl -autoconnect
  encfs-enabled:
    type: boolean
    default: False
    description: "Encrypt the weechat folder and logs at rest"
  encfs-password:
    type: string
    default: ""
    description: "Encryption password, must be provided if encryption is enabled"
  proxy-via-hostname:
    type: boolean
    default: false
    description: "If true use fqdn with the reverse proxy, if false use ip address"
